name: terratechgarden
description: A Flutter app for terrarium business
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  auto_route: ^9.2.2
  equatable: ^2.0.5
  http: ^1.2.2
  firebase_auth: ^5.6.0
  firebase_core: ^3.15.0 
  google_sign_in: ^6.2.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^9.2.2
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.3
  font_awesome_flutter: ^10.7.0
  animate_do: ^3.3.4

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon/icon.png"

flutter:
  uses-material-design: true